chore: release

diff --git a/dev/bin/release-new-version b/dev/bin/release-new-version
--- a/dev/bin/release-new-version
+++ b/dev/bin/release-new-version
@@ -4,13 +4,13 @@
 
 function get-version --description "Gets the current version of the project from the cabal file."
     cabal run findata-transcoder version
+    or begin
+        echo "Could not get the current version. Aborting."
+        exit 1
+    end
 end
 
 set OLD_VERSION (get-version)
-or begin
-    echo "Could not get the current version. Aborting."
-    exit 0
-end
 
 echo "Bump up the new version in package.yaml. Once done, confirm [y/n]":
 read confirm
